### ISSUE TITLE
Showcase route returns 404 in production

### ISSUE THREAD

**Issue by MeirionHughes** [crisbal/vue-webpack-ssr-fully-featured#1]
In development the show-case route is working as expected. but after a build and running with `npm start` the showcase route returns 404. 

Nice work with the template btw - certainly very helpful. 👍

**Comment by crisbal** [comment]
Hey,

this is the expected behavior. Just to see if it was possible I enable the showcase route only for development. 

Take a look here for more info: https://github.com/crisbal/vue-webpack-ssr-fully-featured/blob/master/src/router/index.js#L16

```javascript
if (process.env.NODE_ENV !== "production") {
	const Showcase = () => System.import("views/Showcase")
	const ShowcaseFetchError = () => System.import("views/ShowcaseFetchError")

	routes.push({ path: "/showcase", component: Showcase })
	routes.push({ path: "/showcase/fetch-error", component: ShowcaseFetchError })
}
```

**Comment by MeirionHughes** [comment]
ah ok; sorry it seemed counter intuitive that it would be missing. 

btw, I think `System.import` was [depreciated in favor of](https://github.com/tc39/proposal-dynamic-import) `import()`

**Comment by crisbal** [comment]
Thanks for pointing that out, I will give it a try.
