### ISSUE TITLE
How to implement lang switching with static localization?

### ISSUE THREAD

**Issue by vsorrokin** [crisbal/vue-webpack-ssr-fully-featured#11]
Do somebody have an idea how to make site lang switching? Only one possible solution which I see in this project is to build multiple times for every used language and save them to folders ru/en/it etc. Or always use dynamic localization with some caching if possible (maybe v-t directive?). Not sure how to make this good.

**Comment by crisbal** [comment]
Hey there, the best way would be to build multiple times for each language and serve each language on its own subdomain
