### ISSUE TITLE
Serverside VueJS related memory leak

### ISSUE THREAD

**Issue by editedredx** [crisbal/vue-webpack-ssr-fully-featured#12]
Tested using node 8.4.0 and 9.5.0.

clean install start using `node run start` to rule out Webpack related stuff.
(only added an --inspect)

Took heap snapshots using chrome debugger. 

10.9 MB - after server start
12.8 MB - after first request of homepage html
14.1 MB - after twenty more requests of homepage html
15.4 MB - after twenty more requests of homepage html
16.7 MB - after twenty more requests of homepage html

As you can see approximately 1.3 MB is added in 20 requests of homepage html. Forcing a garbage collection does not seem to change anything.

Still looking into it, I'll update what I can find.

**Comment by crisbal** [comment]
Hey, thanks for reporting this. I would have never noticed it. I will also look into this, if you have any more information please keep it coming.

**Comment by editedredx** [comment]
Problems seems to be fixed when moving `
const i18n = new VueI18n({
	locale: "main",
	messages
})` to inside of the `createApp` function in `app.js` 

I'll continue this tomorrow to make sure though.
