### ISSUE TITLE
vue devtool in production mode

### ISSUE THREAD

**Issue by raymayemir** [crisbal/vue-webpack-ssr-fully-featured#16]
Hello! Why devtool running in production mode ?
console show  `You are running Vue in development mode.`

`Vue.config.productionTip = false` doesn't seem to be working

**Comment by crisbal** [comment]
Hmm, do you run the server with `npm run build; npm run start`?

**Comment by raymayemir** [comment]
Yes

**Comment by crisbal** [comment]
![deepin-screenshot kkuihi](https://user-images.githubusercontent.com/2728038/36776771-4de13a10-1c67-11e8-8634-d38201bea66b.png)
As you can see I don't have the issue. Try force-refreshing the browser / clearing cache

**Comment by raymayemir** [comment]
<img width="1568" alt="2018-02-28 14 14 14" src="https://user-images.githubusercontent.com/5638101/36777011-033b5a38-1c92-11e8-90c2-305a4b5abaf2.png">

**Comment by raymayemir** [comment]
<img width="331" alt="2018-02-28 14 13 07" src="https://user-images.githubusercontent.com/5638101/36777013-0e5f14c2-1c92-11e8-8f1f-4349c8cfedb3.png">

**Comment by crisbal** [comment]
I think it is still has some cached files. Try using an incognito window and test for the same thing.

**Comment by crisbal** [comment]
As you can see the browser is requesting `/__webpack_html` which is hot module reloading, which means that the browser believes this is a development environment

**Comment by raymayemir** [comment]
Yes, maybe a bug on my part.
I re-ran nfs run build & npm run start
and webpack_hmr not show
but would still can watch dev tools

**Comment by crisbal** [comment]
Does the same happen in Incognito Window? (CTRL+SHIFT+N) ?

**Comment by raymayemir** [comment]
no result

**Comment by raymayemir** [comment]
which can affect except the cache ?

**Comment by raymayemir** [comment]
tested on safari 
console show You are running Vue in development mode.

**Comment by crisbal** [comment]
It could be that the environment variable is not correctly set. Or that something is overwriting it. You should try to print the NODE_ENV variable in the server script and see its value.

**Comment by crisbal** [comment]
Can you also try starting from a fresh project/new clone of this project and see if the problem is still there?

**Comment by raymayemir** [comment]
ok

**Comment by raymayemir** [comment]
your repository is in good order

**Comment by raymayemir** [comment]
maybe it's because of new UglifyJsPlugin () ?

**Comment by raymayemir** [comment]
I changed it because of an error in new webpack.optimize.UglifyJsPlugin()

**Comment by raymayemir** [comment]
but console.log(isProduction) showed true and console.log(process.env.NODE_ENV) show production 😳in server.js

**Comment by raymayemir** [comment]
as I understand it does not really need?
`Vue.config.productionTip = false`

**Comment by raymayemir** [comment]
Hi @crisbal ! This error is due to the fact that I used vue/dist/vue.js.
