### ISSUE TITLE
The client-side rendered virtual DOM tree is not matching server-rendered content.

### ISSUE THREAD

**Issue by raymayemir** [crisbal/vue-webpack-ssr-fully-featured#17]
Hi! i have this error when im using like this case 
```
<div class="message">
  <div v-if="isLogin">
    ...
    // user comment form
  </div>
  <div v-else>
    ...
    please sign in to comment
  </div>
</div>
```
So if to remove I not see these mistakes, but I do need to work practically everywhere check if `isLogin`
I have a mode both for guests and for registered users and whether correct exit to change everything on v-show ? because it just gives the style

**Comment by raymayemir** [comment]
Solved! I decided not to use the computed values in the checks

**Comment by distortia** [comment]
@RaiMaemirov Thanks for the update!

**Comment by raymayemir** [comment]
@distortia Do you have the same problem?

**Comment by distortia** [comment]
I ran into the issue in the past. I was just thanking you for posting your
answer!

**Comment by raymayemir** [comment]
@distortia 👍🏼
