### ISSUE TITLE
Q. How to deploy the production build using Nginx alone (without NodeJS)

### ISSUE THREAD

**Issue by sohailalam2** [crisbal/vue-webpack-ssr-fully-featured#9]
I understand that SSR needs NodeJs, but suppose if we want to generate a static files which can be served with Nginx or some other webserver (just like `nuxt generate`), how can we do it?

**Comment by crisbal** [comment]
Hello, you would not use this template then. This is for SSR only. There are many quirks and features (especially async data fetching) that will only work because of SSR. There are plenty of other templates that will let you build only for the browser alone (https://github.com/vuejs-templates)

**Comment by sohailalam2** [comment]
Then how does Nuxt do it - both SSR as well as - *in their words*, **Serverless Static Generated Web Application** ?? https://nuxtjs.org/guide/#static-generated-pre-rendering-

**Comment by crisbal** [comment]
When you build statically with nuxt you get a static copy of the website. This means that the website is "freezed" at that time and is built with the data that is available at that exact moment. If you are building a dynamic website with a lot of data fetching from a backend API then statically building the website won't work, since you would need a static copy each time the API result changes, this is when you would use true SSR.

**Comment by sohailalam2** [comment]
Yes, I get that. You can always populate your webapp with data by doing ajax requests in that case (just like we do for any other modern websites). At the same time, SEO is also covered because you have a crawlable static website. 

Of course, this is a good solution only if your webapp is not updated frequently. At least then the framework would give you a choice whether to build a SSR-only or a Static-only production build. IMHO this is important as well. 

The reason I like your version over Nuxt is the project structure, more freedom and control of how to organize things like router, store etc. (no magic here) and of course lighthouse scores :)

**Comment by crisbal** [comment]
Yes, the "problem" is that it is not really clear how much of the javascript the web crawlers execute (it is still unsure https://www.stephanboyer.com/post/122/does-google-execute-javascript / https://news.ycombinator.com/item?id=13294779).

If the site is really content dependent having a static "empty" website is not much of an option in terms of SEO, considering the above links.
